import type { Metadata } from 'next';
// Import desired fonts ONLY from next/font/google
import { Inter, Roboto_Mono } from 'next/font/google';
import './globals.css';

// Initialize Inter (sans-serif)
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // Define CSS variable for Inter
  // Add weights if needed, e.g., weight: ['400', '700']
});

// Initialize Roboto Mono (mono-serif)
const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  weight: ['400', '700'], // Keep weights for Roboto Mono
  variable: '--font-roboto-mono', // Define CSS variable for Roboto Mono
});

export const metadata: Metadata = {
  title: 'Sharky Script Maker',
  description: 'Generated by Firebase Studio', // Consider updating description
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply font variables for the selected Google Fonts */}
      {/* Ensure your tailwind.config.ts maps font families (e.g., sans, mono) */}
      {/* to these variables (--font-inter, --font-roboto-mono) */}
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
