import type { Metadata } from 'next';
// Assuming Geist and Roboto_Mono are correctly imported from next/font/google
import { Geist_Sans } from 'next/font/google'; // Corrected import name if using Geist package
import { Geist_Mono } from 'next/font/google';
import { Roboto_Mono } from 'next/font/google';
import './globals.css';

// Initialize fonts with variables
const geistSans = Geist_Sans({ // Use the correct export name
  variable: '--font-geist-sans',
  subsets: ['latin'],
  // Add weight options if needed/available
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  // Add weight options if needed/available
});

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto-mono',
});

export const metadata: Metadata = {
  title: 'Sharky Script Maker',
  description: 'Generated by Firebase Studio', // Consider updating description
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply font variables and base Tailwind antialiasing */}
      {/* REMOVED the 'roblox-script-forge' class to avoid global neon effects */}
      <body className={`${robotoMono.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
